const alternativeLetters = {
    a: ["4", "@"],
    // b: [],
    c: ["ć"],
    // d: [],
    e: ["3"],
    // f: [],
    g: ["6"],
    h: ["ch"],
    i: ["1"],
    // j: [],
    // k: [],
    l: ["ł"],
    // m: [],
    n: ["ń"],
    o: ["0"],
    ó: ["u", "00", "oo", "0o", "o0"],
    // p: [],
    // q: [],
    // r: [],
    // s: [],
    // t: [],
    u: ["ó", "00", "oo", "0o", "o0"],
    // v: [],
    // w: [],
    // x: [],
    // y: [],
    // z: [],
    "/": ["-", "_", "."],
}

const bannedWords = [
    // czarnoskórzy
    "nigger",
    "niggers",
    "nigers",
    "nigga",
    "niga",
    "nyga",
    "czarnuh",
    "czarnoskórych",
    "czarno/skórych",
    "czarnymen",

    // nasizm/fasyzm/komunizm
    "hitler",
    "hit/ler",
    "adolf",

    // kysowate
    "zdechnij",
    "zdehnij",
    "umrzyj",
    "zabij sie",
    "zabij się",
    "żyd",
    "żyda",
    "żydzi",
    "żydów",

    // inne zwyzywane
    "kurwo",
    "smiec",
    "cwel",
    "pedal",
    "pierdolony",
    "pojebany",
    //---
    //reszta do segregacji
    "idioto",
    "kurewko",
    "kurewka",
    "zjebany",
    "zjebie",
    "huju",
    "szmato",
    "przyjeb",
    "przyjebany",
    "rozjebany",
    "rozjebana",
    "idiotka",
    "zjebana",
    "pierdolona",
    "szmata",
    "hujowa",
    "hujowy",
    "przyjebana",
    "rozjebana",
    "kurwą",
    "idiotką",
    "gin",
    "debil",
    "debilka",
    "chuj mu",
    "chuj jej",
    "chuj ci",
    "zgin",
    "zgiń",
    "kys",
    "gkys",
    "pedale",
    "chuju",
    "dziwko",
    "dziwką",
    "idiotko",
    "popierdolona",
    "popierdolony",
    "pierdolona",
    "debilko",
    "dziwka",
    "szmato",
    "czarnuchu",
    "czarnuhu",
    "niggerze",
    "nigerze",
    "cwelu",
    "cweloza",
    "zjeb",
    "zjebana",
    "przyjebana",
    "kill yourself",
    "kill your self",
    "kil yourself",
    "kil your self",
    "sex",
    "sexu",
    "seks",
    "seksu",
    "aggin",
    "lgbt",
    "nig/er",
    "nigg/er",
    "nudes",
    "nygga",
    "reggin",
    "sedun",
    "sta/lin",
    "tbgl",
]

function checkAnyBadWords(text) {
    for (let i = 0; i < bannedWords.length; i++) {
        const regex = new RegExp(`([^a-z0-9])${bannedWords[i].replace(/\(/, "\\(").replace(/\)/, "\\)")}([^a-z0-9])|^(${bannedWords[i]}(?: *))+`, "i")
        if (regex.test(text)) {
            return { checked: true, badWord: bannedWords[i] }
        }
    }
    return { checked: false }
}

module.exports = { checkAnyBadWords }
